export const GET_TRENDING = 'GET_TRENDING';
export const GET_NETFLIX_ORIGINALS = 'GET_NETFLIX_ORIGINALS';
export const GET_TOP_RATED = 'GET_TOP_RATED';
export const GET_ACTION_MOVIES = 'GET_ACTION_MOVIES';
export const GET_COMEDY_MOVIES = 'GET_COMEDY_MOVIES';
export const GET_HORROR_MOVIES = 'GET_HORROR_MOVIES';
export const GET_ROMANCE_MOVIES = 'GET_ROMANCE_MOVIES';
export const GET_DOCUMENTARIES = 'GET_DOCUMENTARIES';
// movie details
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAIL = 'GET_MOVIE_DETAILS_FAIL';
// search
export const GET_SEARCH_MOVIE = 'GET_SEARCH_MOVIE';
export const GET_SEARCH_MOVIE_FAIL = 'GET_SEARCH_MOVIE_FAIL';
export const GET_SEARCH_MOVIE_SUCCESS = 'GET_SEARCH_MOVIE_SUCCESS';
